### PR TITLE
Make ComponentSystem and Default Material, Application scope

### PR DESCRIPTION
**Pull request by OlegGedzjuns**
Currently, ComponentSystem is global and orchestrates systems globally. This makes multi-application usage somewhat difficult, especially when applications have to be added/destroyed constantly and have various update rates.

Also, default material was global, this lead to an issue when in multi-application case we destroy one application, this lead to default material destruction which then broke other applications that are still running.

This change improves the usage of an engine in a render-less server-side context.
As well as the client-side cases with multiple applications on a page.

There are no behavior changes.
Please test on your various projects with this build.

Fixes: https://github.com/playcanvas/engine/issues/3461

I confirm I have read the [contributing guidelines](https://github.com/playcanvas/engine/blob/master/.github/CONTRIBUTING.md) and signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

### CODE REVIEW

**Comment by willeastcott** [comment]
What's your verdict on this PR @vkalpias? I'd like it to go out with the next minor release if possible?

**Comment by alamboley** [comment]
Hello, running into an issue when upgrade from 1.47 to 1.48 or later:
`pc.ComponentSystem.initialize is not a function` seems to be related to this PR.

```js
assetsToLoad.forEach(function(assetToLoad) {
        assetToLoad.ready(function(asset) {
            count++;
            loadingElement.width = 200 * (count / assetsToLoad.length);
            if (count == assetsToLoad.length) {
                this.app.scenes.loadScene(sceneToLoad.url, function (err2, scene2) {
                    if (!err2) {
                        oldHierarchy.destroy();
                        pc.ComponentSystem.initialize(scene2.root);
                        pc.ComponentSystem.postInitialize(scene2.root);
                    } else
                        console.error(err2);
                }.bind(this));
            }
        }.bind(this));
        this.app.assets.load(assetToLoad);
    }.bind(this));
}
```

How this code should be updated?

**Comment by mvaligursky** [comment]
I believe this is what you need to call:
```
     // before callback:
     const self = this;

      // inside callback
      self.app.systems.fire('initialize', scene2.root);
      self.app.systems.fire('postInitialize', scene2.root);

```

**Comment by willeastcott** [comment]
Actually, you don't need to cache `this` in `self` because the function has `.bind(this)`.

**Comment by alamboley** [comment]
Thanks for the code @mvaligursky! I'm a bit worried firing an event is less intuitive than calling a method, and hard to have code completion in editor with that kind of thing... but it works fine!

**Comment by Maksims** [comment]
Those events are actually not public, so use them with caution.

**Comment by willeastcott** [comment]
Yeah, while that code change may work, this isn't public API. This looks to me like there's either a bug or a hole in the API. Can anyone who knows more than me comment?

**Comment by yaustar** [comment]
loadScene used to be the only way to load a scene hierarchy and settings with one HTTP request. It was also exposed for engine only uses as it was the only way to load the first scene IIRC.

In the API docs, the function is flagged as an internal function: https://developer.playcanvas.com/api/pc.SceneRegistry.html#loadScene

Now that it is possible to preload the scene data, it is possible (a bit verbose) to load both the scene hierarchy and settings via one HTTP call and using the public API 

```
var self = this;
this.scene = this.app.scenes.find(this.sceneName);

// Load the scene data via HTTP
this.app.scenes.loadSceneData(this.scene, function (err, sceneItem) {
    if (err) {
        console.error(err);
    } else {
        // Get a reference to the scene's root object
        var oldHierarchy = self.app.root.findByName('Root');
        oldHierarchy.destroy();

        // Load both the hierarchy and scene settings
        self.app.scenes.loadSceneHierarchy(self.scene, function() {});
        self.app.scenes.loadSceneSettings(self.scene, function() {});

        // Unload the data
        self.app.scenes.unloadSceneData(self.scene);
    }
});
```
